version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkmystar-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ConnectionStrings__CheckMyStarConnection: "Server=sqlserver;Database=CheckMyStar;User Id=sa;Password=@Eb23#Ab28%Mb15!;TrustServerCertificate=True;"
    expose:
      - "8080"
    depends_on:
      - sqlserver
    restart: always

  angular:
    build:
      context: ./CheckMyStar.Angular
    container_name: checkmystar-angular
    expose:
      - "80"
    restart: always

  nginx:
    image: nginx:latest
    container_name: checkmystar-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - angular
      - api
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@Eb23#Ab28%Mb15!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

volumes:
  sql_data:
